name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.svg
          base: header, activity, community, repositories, topics, stargazers, contributions
          plugins: |
            - base:
                avatar: true
                bio: true
                name: true
                company: true
                location: true
                website: true
            - activity:
                commits: 365
                iso: true
                days: 14
            - community:
                issues: 10
                prs: 10
            - repositories:
                limit: 8
                starred: 3
            - topics:
                limit: 10
            - stargazers:
                limit: 10
            - contributions:
                referer: true
          options: |
            --user asiimwe-dev
            --render stats
            --template terminal
            --color-scheme dark
