name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.svg
          template: classic
          base: ""
          config_timezone: Africa/Kampala
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
